
import Boolean from "./types/boolean";
import String from "./types/string";
import __Type from "./types/type";
import __TypeKind from "./types/type-kind";
import __Field from "./types/field";
import __InputValue from "./types/input-value";
import __EnumValue from "./types/enum-value";
import QueryRoot from "./types/query-root";
import Node from "./types/node";
import ID from "./types/id";
import Customer from "./types/customer";
import DateTime from "./types/date-time";
import MailingAddress from "./types/mailing-address";
import Float from "./types/float";
import MailingAddressConnection from "./types/mailing-address-connection";
import PageInfo from "./types/page-info";
import MailingAddressEdge from "./types/mailing-address-edge";
import Int from "./types/int";
import OrderConnection from "./types/order-connection";
import OrderEdge from "./types/order-edge";
import Order from "./types/order";
import Money from "./types/money";
import CurrencyCode from "./types/currency-code";
import URL from "./types/url";
import OrderLineItemConnection from "./types/order-line-item-connection";
import OrderLineItemEdge from "./types/order-line-item-edge";
import OrderLineItem from "./types/order-line-item";
import MoneyV2 from "./types/money-v-2";
import Decimal from "./types/decimal";
import ProductVariant from "./types/product-variant";
import WeightUnit from "./types/weight-unit";
import Image from "./types/image";
import CropRegion from "./types/crop-region";
import ImageContentType from "./types/image-content-type";
import SelectedOption from "./types/selected-option";
import Product from "./types/product";
import CollectionConnection from "./types/collection-connection";
import CollectionEdge from "./types/collection-edge";
import Collection from "./types/collection";
import HTML from "./types/html";
import ProductConnection from "./types/product-connection";
import ProductEdge from "./types/product-edge";
import ProductCollectionSortKeys from "./types/product-collection-sort-keys";
import ImageConnection from "./types/image-connection";
import ImageEdge from "./types/image-edge";
import ProductImageSortKeys from "./types/product-image-sort-keys";
import SelectedOptionInput from "./types/selected-option-input";
import ProductOption from "./types/product-option";
import ProductVariantConnection from "./types/product-variant-connection";
import ProductVariantEdge from "./types/product-variant-edge";
import ProductVariantSortKeys from "./types/product-variant-sort-keys";
import Attribute from "./types/attribute";
import OrderSortKeys from "./types/order-sort-keys";
import Shop from "./types/shop";
import PaymentSettings from "./types/payment-settings";
import CountryCode from "./types/country-code";
import CardBrand from "./types/card-brand";
import DigitalWallet from "./types/digital-wallet";
import Domain from "./types/domain";
import ShopPolicy from "./types/shop-policy";
import BlogConnection from "./types/blog-connection";
import BlogEdge from "./types/blog-edge";
import Blog from "./types/blog";
import ArticleConnection from "./types/article-connection";
import ArticleEdge from "./types/article-edge";
import Article from "./types/article";
import ArticleAuthor from "./types/article-author";
import CommentConnection from "./types/comment-connection";
import CommentEdge from "./types/comment-edge";
import Comment from "./types/comment";
import CommentAuthor from "./types/comment-author";
import BlogSortKeys from "./types/blog-sort-keys";
import ArticleSortKeys from "./types/article-sort-keys";
import CollectionSortKeys from "./types/collection-sort-keys";
import ProductSortKeys from "./types/product-sort-keys";
import StringConnection from "./types/string-connection";
import StringEdge from "./types/string-edge";
import Mutation from "./types/mutation";
import CheckoutAttributesUpdatePayload from "./types/checkout-attributes-update-payload";
import UserError from "./types/user-error";
import Checkout from "./types/checkout";
import CheckoutLineItemConnection from "./types/checkout-line-item-connection";
import CheckoutLineItemEdge from "./types/checkout-line-item-edge";
import CheckoutLineItem from "./types/checkout-line-item";
import ShippingRate from "./types/shipping-rate";
import AvailableShippingRates from "./types/available-shipping-rates";
import AppliedGiftCard from "./types/applied-gift-card";
import CheckoutAttributesUpdateInput from "./types/checkout-attributes-update-input";
import AttributeInput from "./types/attribute-input";
import CheckoutCompleteFreePayload from "./types/checkout-complete-free-payload";
import CheckoutCompleteWithCreditCardPayload from "./types/checkout-complete-with-credit-card-payload";
import Payment from "./types/payment";
import CreditCard from "./types/credit-card";
import Transaction from "./types/transaction";
import TransactionKind from "./types/transaction-kind";
import TransactionStatus from "./types/transaction-status";
import CreditCardPaymentInput from "./types/credit-card-payment-input";
import MailingAddressInput from "./types/mailing-address-input";
import CheckoutCompleteWithTokenizedPaymentPayload from "./types/checkout-complete-with-tokenized-payment-payload";
import TokenizedPaymentInput from "./types/tokenized-payment-input";
import CheckoutCreatePayload from "./types/checkout-create-payload";
import CheckoutCreateInput from "./types/checkout-create-input";
import CheckoutLineItemInput from "./types/checkout-line-item-input";
import CheckoutCustomerAssociatePayload from "./types/checkout-customer-associate-payload";
import CheckoutCustomerDisassociatePayload from "./types/checkout-customer-disassociate-payload";
import CheckoutDiscountCodeApplyPayload from "./types/checkout-discount-code-apply-payload";
import CheckoutEmailUpdatePayload from "./types/checkout-email-update-payload";
import CheckoutGiftCardApplyPayload from "./types/checkout-gift-card-apply-payload";
import CheckoutGiftCardRemovePayload from "./types/checkout-gift-card-remove-payload";
import CheckoutLineItemsAddPayload from "./types/checkout-line-items-add-payload";
import CheckoutLineItemsRemovePayload from "./types/checkout-line-items-remove-payload";
import CheckoutLineItemsUpdatePayload from "./types/checkout-line-items-update-payload";
import CheckoutLineItemUpdateInput from "./types/checkout-line-item-update-input";
import CheckoutShippingAddressUpdatePayload from "./types/checkout-shipping-address-update-payload";
import CheckoutShippingLineUpdatePayload from "./types/checkout-shipping-line-update-payload";
import CustomerAccessTokenCreatePayload from "./types/customer-access-token-create-payload";
import CustomerAccessToken from "./types/customer-access-token";
import CustomerAccessTokenCreateInput from "./types/customer-access-token-create-input";
import CustomerAccessTokenDeletePayload from "./types/customer-access-token-delete-payload";
import CustomerAccessTokenRenewPayload from "./types/customer-access-token-renew-payload";
import CustomerActivatePayload from "./types/customer-activate-payload";
import CustomerActivateInput from "./types/customer-activate-input";
import CustomerAddressCreatePayload from "./types/customer-address-create-payload";
import CustomerAddressDeletePayload from "./types/customer-address-delete-payload";
import CustomerAddressUpdatePayload from "./types/customer-address-update-payload";
import CustomerCreatePayload from "./types/customer-create-payload";
import CustomerCreateInput from "./types/customer-create-input";
import CustomerDefaultAddressUpdatePayload from "./types/customer-default-address-update-payload";
import CustomerRecoverPayload from "./types/customer-recover-payload";
import CustomerResetPayload from "./types/customer-reset-payload";
import CustomerResetInput from "./types/customer-reset-input";
import CustomerUpdatePayload from "./types/customer-update-payload";
import CustomerUpdateInput from "./types/customer-update-input";
import __Schema from "./types/schema";
import __Directive from "./types/directive";
import __DirectiveLocation from "./types/directive-location";
const Types = {
  types: {}
};
Types.types["Boolean"] = Boolean;
Types.types["String"] = String;
Types.types["__Type"] = __Type;
Types.types["__TypeKind"] = __TypeKind;
Types.types["__Field"] = __Field;
Types.types["__InputValue"] = __InputValue;
Types.types["__EnumValue"] = __EnumValue;
Types.types["QueryRoot"] = QueryRoot;
Types.types["Node"] = Node;
Types.types["ID"] = ID;
Types.types["Customer"] = Customer;
Types.types["DateTime"] = DateTime;
Types.types["MailingAddress"] = MailingAddress;
Types.types["Float"] = Float;
Types.types["MailingAddressConnection"] = MailingAddressConnection;
Types.types["PageInfo"] = PageInfo;
Types.types["MailingAddressEdge"] = MailingAddressEdge;
Types.types["Int"] = Int;
Types.types["OrderConnection"] = OrderConnection;
Types.types["OrderEdge"] = OrderEdge;
Types.types["Order"] = Order;
Types.types["Money"] = Money;
Types.types["CurrencyCode"] = CurrencyCode;
Types.types["URL"] = URL;
Types.types["OrderLineItemConnection"] = OrderLineItemConnection;
Types.types["OrderLineItemEdge"] = OrderLineItemEdge;
Types.types["OrderLineItem"] = OrderLineItem;
Types.types["MoneyV2"] = MoneyV2;
Types.types["Decimal"] = Decimal;
Types.types["ProductVariant"] = ProductVariant;
Types.types["WeightUnit"] = WeightUnit;
Types.types["Image"] = Image;
Types.types["CropRegion"] = CropRegion;
Types.types["ImageContentType"] = ImageContentType;
Types.types["SelectedOption"] = SelectedOption;
Types.types["Product"] = Product;
Types.types["CollectionConnection"] = CollectionConnection;
Types.types["CollectionEdge"] = CollectionEdge;
Types.types["Collection"] = Collection;
Types.types["HTML"] = HTML;
Types.types["ProductConnection"] = ProductConnection;
Types.types["ProductEdge"] = ProductEdge;
Types.types["ProductCollectionSortKeys"] = ProductCollectionSortKeys;
Types.types["ImageConnection"] = ImageConnection;
Types.types["ImageEdge"] = ImageEdge;
Types.types["ProductImageSortKeys"] = ProductImageSortKeys;
Types.types["SelectedOptionInput"] = SelectedOptionInput;
Types.types["ProductOption"] = ProductOption;
Types.types["ProductVariantConnection"] = ProductVariantConnection;
Types.types["ProductVariantEdge"] = ProductVariantEdge;
Types.types["ProductVariantSortKeys"] = ProductVariantSortKeys;
Types.types["Attribute"] = Attribute;
Types.types["OrderSortKeys"] = OrderSortKeys;
Types.types["Shop"] = Shop;
Types.types["PaymentSettings"] = PaymentSettings;
Types.types["CountryCode"] = CountryCode;
Types.types["CardBrand"] = CardBrand;
Types.types["DigitalWallet"] = DigitalWallet;
Types.types["Domain"] = Domain;
Types.types["ShopPolicy"] = ShopPolicy;
Types.types["BlogConnection"] = BlogConnection;
Types.types["BlogEdge"] = BlogEdge;
Types.types["Blog"] = Blog;
Types.types["ArticleConnection"] = ArticleConnection;
Types.types["ArticleEdge"] = ArticleEdge;
Types.types["Article"] = Article;
Types.types["ArticleAuthor"] = ArticleAuthor;
Types.types["CommentConnection"] = CommentConnection;
Types.types["CommentEdge"] = CommentEdge;
Types.types["Comment"] = Comment;
Types.types["CommentAuthor"] = CommentAuthor;
Types.types["BlogSortKeys"] = BlogSortKeys;
Types.types["ArticleSortKeys"] = ArticleSortKeys;
Types.types["CollectionSortKeys"] = CollectionSortKeys;
Types.types["ProductSortKeys"] = ProductSortKeys;
Types.types["StringConnection"] = StringConnection;
Types.types["StringEdge"] = StringEdge;
Types.types["Mutation"] = Mutation;
Types.types["CheckoutAttributesUpdatePayload"] = CheckoutAttributesUpdatePayload;
Types.types["UserError"] = UserError;
Types.types["Checkout"] = Checkout;
Types.types["CheckoutLineItemConnection"] = CheckoutLineItemConnection;
Types.types["CheckoutLineItemEdge"] = CheckoutLineItemEdge;
Types.types["CheckoutLineItem"] = CheckoutLineItem;
Types.types["ShippingRate"] = ShippingRate;
Types.types["AvailableShippingRates"] = AvailableShippingRates;
Types.types["AppliedGiftCard"] = AppliedGiftCard;
Types.types["CheckoutAttributesUpdateInput"] = CheckoutAttributesUpdateInput;
Types.types["AttributeInput"] = AttributeInput;
Types.types["CheckoutCompleteFreePayload"] = CheckoutCompleteFreePayload;
Types.types["CheckoutCompleteWithCreditCardPayload"] = CheckoutCompleteWithCreditCardPayload;
Types.types["Payment"] = Payment;
Types.types["CreditCard"] = CreditCard;
Types.types["Transaction"] = Transaction;
Types.types["TransactionKind"] = TransactionKind;
Types.types["TransactionStatus"] = TransactionStatus;
Types.types["CreditCardPaymentInput"] = CreditCardPaymentInput;
Types.types["MailingAddressInput"] = MailingAddressInput;
Types.types["CheckoutCompleteWithTokenizedPaymentPayload"] = CheckoutCompleteWithTokenizedPaymentPayload;
Types.types["TokenizedPaymentInput"] = TokenizedPaymentInput;
Types.types["CheckoutCreatePayload"] = CheckoutCreatePayload;
Types.types["CheckoutCreateInput"] = CheckoutCreateInput;
Types.types["CheckoutLineItemInput"] = CheckoutLineItemInput;
Types.types["CheckoutCustomerAssociatePayload"] = CheckoutCustomerAssociatePayload;
Types.types["CheckoutCustomerDisassociatePayload"] = CheckoutCustomerDisassociatePayload;
Types.types["CheckoutDiscountCodeApplyPayload"] = CheckoutDiscountCodeApplyPayload;
Types.types["CheckoutEmailUpdatePayload"] = CheckoutEmailUpdatePayload;
Types.types["CheckoutGiftCardApplyPayload"] = CheckoutGiftCardApplyPayload;
Types.types["CheckoutGiftCardRemovePayload"] = CheckoutGiftCardRemovePayload;
Types.types["CheckoutLineItemsAddPayload"] = CheckoutLineItemsAddPayload;
Types.types["CheckoutLineItemsRemovePayload"] = CheckoutLineItemsRemovePayload;
Types.types["CheckoutLineItemsUpdatePayload"] = CheckoutLineItemsUpdatePayload;
Types.types["CheckoutLineItemUpdateInput"] = CheckoutLineItemUpdateInput;
Types.types["CheckoutShippingAddressUpdatePayload"] = CheckoutShippingAddressUpdatePayload;
Types.types["CheckoutShippingLineUpdatePayload"] = CheckoutShippingLineUpdatePayload;
Types.types["CustomerAccessTokenCreatePayload"] = CustomerAccessTokenCreatePayload;
Types.types["CustomerAccessToken"] = CustomerAccessToken;
Types.types["CustomerAccessTokenCreateInput"] = CustomerAccessTokenCreateInput;
Types.types["CustomerAccessTokenDeletePayload"] = CustomerAccessTokenDeletePayload;
Types.types["CustomerAccessTokenRenewPayload"] = CustomerAccessTokenRenewPayload;
Types.types["CustomerActivatePayload"] = CustomerActivatePayload;
Types.types["CustomerActivateInput"] = CustomerActivateInput;
Types.types["CustomerAddressCreatePayload"] = CustomerAddressCreatePayload;
Types.types["CustomerAddressDeletePayload"] = CustomerAddressDeletePayload;
Types.types["CustomerAddressUpdatePayload"] = CustomerAddressUpdatePayload;
Types.types["CustomerCreatePayload"] = CustomerCreatePayload;
Types.types["CustomerCreateInput"] = CustomerCreateInput;
Types.types["CustomerDefaultAddressUpdatePayload"] = CustomerDefaultAddressUpdatePayload;
Types.types["CustomerRecoverPayload"] = CustomerRecoverPayload;
Types.types["CustomerResetPayload"] = CustomerResetPayload;
Types.types["CustomerResetInput"] = CustomerResetInput;
Types.types["CustomerUpdatePayload"] = CustomerUpdatePayload;
Types.types["CustomerUpdateInput"] = CustomerUpdateInput;
Types.types["__Schema"] = __Schema;
Types.types["__Directive"] = __Directive;
Types.types["__DirectiveLocation"] = __DirectiveLocation;
Types.queryType = "QueryRoot";
Types.mutationType = "Mutation";
Types.subscriptionType = null;

function recursivelyFreezeObject(structure) {
  Object.getOwnPropertyNames(structure).forEach(key => {
    const value = structure[key];
    if (value && typeof value === 'object') {
      recursivelyFreezeObject(value);
    }
  });
  Object.freeze(structure);
  return structure;
}

export default recursivelyFreezeObject(Types);