export default {
    GET_CASES: 'GET_CASES',
    GET_SIMPLE_CASES: 'GET_SIMPLE_CASES',
    GET_CASE: 'GET_CASE',
    POST_CASE: 'POST_CASE',
    DELETE_CASE: 'DELETE_CASE',
    UPDATE_CASE: 'UPDATE_CASE',
    ADD_TO_CART: 'ADD_TO_CART',
    NULL_CASE_LIST: 'NULL_CASE_LIST',

}

